### ISSUE TITLE
question about use case of this library

### ISSUE THREAD

**Issue by yihuang** [prysmaticlabs/gohashtree#14]
gohashtree optimizations assume the branch node's hash is computed as `sha256(left hash | right hash)`, but idiomatic merkle tree setup need to at least encode the domain type into the content: `sha256(1 | left hash | right hash)`, the `1` prefix is to denote a branch node, so the content won't be exactly 64bytes. And it can't be applied to leaf nodes as well if the leaf content is variable length, right?
So I wonder what's the ideal use case for this library.

Or I wonder what's the security implications if we drop the domain type prefix, when building a merkle tree.

**Comment by potuz** [comment]
This is correct, this library is optimized to 64 bytes inputs and moreover, contiguous chunks of 64 bytes pairs. If the caller doensn't have this structure then this library is useless. 

Merkle trees in Ethereum's SSZ specification for example are the perfect candidate for this library usage. Closing this issue, please feel free to reopen if there are remaining questions.
